### ISSUE TITLE
[L] Ability to add and edit sub-areas in A&R

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/bcparks-ar-admin#427]
#### Description:

As an administrator, I want to be able to add and update sub-areas so that my park information and data stays up-to-date. 

Edit - Moving 'edit subarea' functionality to new ticket.

#### Acceptance Criteria:

Given I am an administrator
When I am on the home screen
Then I see an action card called 'Manage subareas'

Given I am an administrator
When I am looking at the menu
Then I see a tab called Add/Edit Subareas that allows me to get to the correct data entry page

Given I am an administrator
When I am on the Add new subarea tab
Then I am able to enter relevant data related to the sub-area

~~Given I am an administrator
When I am on the Edit subarea tab
Then I am able to edit relevant data related to that subarea~~

Given I am an administrator
When I submit a new subarea ~~or edit an existing~~
And I see a pop-up confirming the details of my submission
Then I can either cancel or save my data

~~Given I am an administrator
When I am editing a subarea
Then I am not able to edit the ORC or Park Name (it is grey out)~~

#### Development Checklist:

- [x] Only visible/accessible by administrators
  - [x] "Manage Subareas" is a navigation item on Home screen
  - [x] "Manage Subareas" is a navigation item on left-side menu
- [x] The two options "Add" and "Edit" option on page and changes between Add fields and Subarea search

**Add Subarea**
Fields for adding a new subarea
- [x] ORCS
- [x] Park Name
- [x] Region
- [x] Section
- [x] Management area
- [x] Bundle
- [x] Subarea name
- [x] Activities (dropdown list)
- [x] User can add one or more activities
- [x] User can remove activities

- [x] Pop-up appears to confirm details of created Subarea when selecting Submit
- [x] Selecting Save will save the data
- [x] Selecting Cancel will go back to editing the fields (close pop-up box)

#### Dependencies

- Blocked by https://github.com/bcgov/bcparks-ar-admin/issues/395
- Blocking

**Wireframe(s):**

- [Figma designs](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=6893-37896)
- Figma, [home page menu updates](https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=5933-36664)

**Workflows:**

#### Notes:
- Menu title goes from Add/Edit Subarea to Manage Subarea > confirm if that is correct. 
-

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

**Comment by Dianadec** [comment]
Refinement notes:
In designs, the blue sidebar should say "Manage Subareas" in each one.

**Comment by cameronpettit** [comment]
Question about these designs @LindsayMacfarlane @Dianadec 

There's a couple of fields shown that appear to be text fields, but I am not sure we should be giving users the ability to type their entry (for consistency's sake).

For example, if you are adding a subarea, the first field that you must fill out should be a typeahead picklist, consisting of all the existing ORCS. We should not be allowing users to add any ORCS number they like because for every ORCS, there must exist a parent park object, otherwise data inconsistencies will occur.

Secondly, if a user picks their ORCS, the name of the park should auto-populate in the second field and should not be able to be changed, regardless of whether it is an `add` or `edit`. We cannot change the park name, so that field should be reference-only.

Thirdly, all subsequent fields are, again, candidates for typeahead picklists as most of the values the fields can assume are part of a very short list of possibilities that we want to keep consistent across all subareas. For example, if a new subarea is part of the South Island region, then if we allow users to type 'South Island' we run the risk of adding typos to the database. In the future when we want to collect all items with `region: South Island`, it may return an incomplete list because not everyone entering data spelled 'South Island' the same way. 

I'm not sure if this has been discussed with the A&R folks already and maybe what I have suggested above IS what the designs intended but to me it isnt totally clear. I would strongly recommend the following:

- For both add and edit pages, the following fields should be typeahead picklists:
  - Orcs
  - Region
  - Section
  - Management Area
  - Bundle
- For both add and edit pages, the above fields cannot be set unless its predecessor is set
- For both add and edit pages, Park Name cannot be edited

There may be more changes I recommend as I am just reacquainting myself with the API

**Comment by Dianadec** [comment]
@cameronpettit  for context re: design decisions, here's the link to the design ticket - see comments :) https://github.com/bcgov/bcparks-ar-admin/issues/395

**Comment by LindsayMacfarlane** [comment]
I agree with your recommendations and was, to some degree, curious if any of those fields (especially ORC and Park Name) could be an automated process. 

A couple of questions:
- How much complexity does adding your suggested recommendations add to this ticket?
- Can we start with a few of your recommended fields (e.g., ORC and park name) or would it be best to do all the ones you recommended?
- Is it better to do this now vs wait once it becomes a business need? (My assumption is if we wait we risk incorrect data entry and adding data issues into the system that we could have prevented).

**Comment by cameronpettit** [comment]
@LindsayMacfarlane I think a large portion of it can be automated, I guess the question is really how easily it will be to do so. 

The ORCS one is easy, I have it set up right now as a typeahead field. We have all the parks in the database, so if I pull all the parks, I get all the ORCS, and I can use it to seed the list of ORCS a user can pick from, and autopopulate the name. 

![Image](https://github.com/user-attachments/assets/1602c34b-380e-4d66-be37-ffc6224f2f87)

![Image](https://github.com/user-attachments/assets/0bd23b5b-9a9a-465e-b622-31d12f69a2b8)

Where it gets a little tricky is the values for Region, Section, Management Area, and Bundle. There is a data hierarchy for these values so we can't mix and match them. All the Regions have their own Sections, all the Sections have their own management areas, etc... so you wouldn't know which Sections you would be able to select until you'd selected a Region. We'd need to know this hierarchy in order to enforce any restrictions, which would involve listing all Regions, Sections, Management Areas and Bundles and assigning them each to their parent. It would be a task for the A&R folks, maybe they already have this hierarchy mapped somewhere.

Personally this isn't something I would release and then fix later due to the data issues you mentioned, but it doesn't mean I have to stop working on it. I'll get as far as I can working in tandem, and if we get that hierarchy then I can implement/release it.

**Comment by LindsayMacfarlane** [comment]
@sallyhaynes @nicolebottoms - see @cameronpettit comments and recommendations. 

Do you have an existing list of the hierarchy's for Region, Section, Management Area, and Bundle?

**Comment by nicolebottoms** [comment]
Region -> section -> management area. bundle is independent of this, and can span over different regions, sections and management areas in one bundle.
let me grab it.

**Comment by nicolebottoms** [comment]
[citywide.xlsx](https://github.com/user-attachments/files/19093160/citywide.xlsx)

in the event of differences between this data and existing A&R data, use A&R as the source of truth.

**Comment by cameronpettit** [comment]
Perfect, thank you @nicolebottoms. This should work nicely.

**Comment by cameronpettit** [comment]
@nicolebottoms is it possible to export that `citiwide.xlsx` document with the park ORCS as well?

**Comment by cameronpettit** [comment]
@LindsayMacfarlane Looking at our API, the logic for the endpoint for subarea edit (`PUT subarea`) actually has not yet been implemented. There does exist an endpoint, but all it does is return `Error: not implemented` - which may have lead to the assumption that the logic was in fact there.

Based on the complexity of the logic currently implemented for subarea create, and on my recollection of the complexity of the A&R data model, I think building out the `PUT subarea` endpoint is not as quick of a win as the earlier issues I've mentioned in this ticket.

The way I see it, there are two options here:
1. Pause the work on this ticket, and create a new ticket to implement the PUT endpoint, blocking this ticket until the endpoint is created.
2. Refactor the AC of this ticket to exclude the subarea edit page - replace the entire form on the edit page to a text box that reads 'coming soon' or something similar. Create a new ticket to implement the PUT endpoint and the subarea edit page, decoupled from the subarea create page.

Personally, option number 2 is probably what I would recommend - almost all the front end work is complete already, including the subarea edit form, but unfortunately the form is useless without the endpoint. What I would do is just feature-flag that form such that it is hidden until the API endpoint is ready, and replaced with that 'coming soon' text. This way, we can release the create subarea functionality now and supplement with the edit functionality later. 

Here's an example of what that would look like:

![Image](https://github.com/user-attachments/assets/667ec351-4881-408a-b6e5-f1f99e51c20c)

Let me know what you would like to do.

**Comment by nicolebottoms** [comment]
> [@nicolebottoms](https://github.com/nicolebottoms) is it possible to export that `citiwide.xlsx` document with the park ORCS as well?

when i was doing it i had a sneaky feeling i should include orcs...

[citywide_export-2025-03-11 with orcs.xlsx](https://github.com/user-attachments/files/19198248/citywide_export-2025-03-11.with.orcs.xlsx)

**Comment by cameronpettit** [comment]
Note - editing AC of this ticket to only include 'add subarea' points. Moving 'edit subarea' points to a new ticket.

Also, regarding my earlier point:

> Secondly, if a user picks their ORCS, the name of the park should auto-populate in the second field and should not be able to be changed, regardless of whether it is an add or edit. We cannot change the park name, so that field should be reference-only.

I realized the purpose of the park name field was to be able to search for the parent park by text instead of by ORCS only. So instead of making the field reference-only, I've allowed both the ORCS and parkname fields to be typeahead picklists, but the minute you select one, the other changes to reflect the correct value.

**Comment by cameronpettit** [comment]
Created https://github.com/bcgov/bcparks-ar-admin/issues/441 and https://github.com/bcgov/bcparks-ar-api/issues/401 to handle the edit issue

**Comment by cameronpettit** [comment]
@manuji once this is deployed to test and prod, we will need a migration.

**Comment by Dianadec** [comment]
@cameronpettit @manuji  reminder that once this is done, we can move #437  out of blocked.

**Comment by manuji** [comment]
Noted with thanks!

**Comment by cameronpettit** [comment]
@manuji I will address point 1) in a new commit. That panel should be closed to everyone but admins.

@LindsayMacfarlane @Dianadec regarding 2) and 3) of Manuji's points, admittedly I took some creative liberties with the designs provided to prevent some data issues:

> 2) Unable to Add a new sub area due to missing dropdown options in "Region" and "Bundle" fields.

@manuji as I stated last week, a migration is needed on promotion to TEST and PROD. I haven't done that yet, I dont know if you asked me to do it already, I might have missed it. That's why youre not seeing any dropdown options. I'll run the migration now and let you know when TEST is ready.

I've made all fields mandatory to prevent users from adding subareas with missing fields in them. There is, for example, 'No Bundle' options to select where no bundle applies. The API will throw an error if these fields are not provided.
Additionally, empty fields will cause problems if we ever want to filter by Region/Section/Management Area/Bundle in the future. By all means I can remove that guardrail to match designs.

The red text is a default property of NGDS-Toolkit's forms, which we are using here. I can remove that too.

> 3) The mandatory fields "Section" and "Management area" are disabled.

As described by Nicole Bottoms earlier in this thread, the fields follow the hierarchy Regions > Sections > Management Areas. You need to pick the parent value before you can pick the child because the child value depends on the parent. The fields are disabled until you pick a parent - but due to the migration not being run there are no fields to select, so they all remain disabled. Again, can remove this guardrail to match designs.

@LindsayMacfarlane please advise on your decisions for 2) and 3).

**Comment by cameronpettit** [comment]
1) addressed in https://github.com/bcgov/bcparks-ar-admin/pull/445 and migration to TEST completed.

**Comment by manuji** [comment]
Tested on TEST: Pending
Following issues could be seen.
1. The options in the dropdown are not sorted alphabetically (not mentioned in the requirement but I am sure client would appreciate it)
2. Incorrect button label displayed on "Add new subarea?" confirmation overlay -> Should show "Save" instead of "Submit". (refer to the figma file for requirement here: https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=6894-62187&t=81AiijMOTeT1Ybeo-1)

<img width="1356" alt="Image" src="https://github.com/user-attachments/assets/647c60a5-1669-4e6b-a094-ffd31ffd6fe9" />

3. The labels and values on the "Add new subarea?" confirmation overlay should be displayed in sentence case except for proper nouns.  
4. The summary of the record displayed on "Add new subarea?" confirmation overlay is not ordered as per the order given on figma nor the order the fields displayed in the Add form.
5. The dropdown options on Add form must be also in sentence case (eg: Day Use must be displayed as Day use). 
6. On Activities field on the Add form, the selected options are not spaced out (Enhancement but not a blocker)

<img width="1426" alt="Image" src="https://github.com/user-attachments/assets/207b7085-94cc-4ab4-a7f4-bd826ff45257" />

----------------------------------------------------
* Confirmed that new subareas are recorded in DynamoDb correctly
* Verified that new sub areas can be seen on Enter data page and can add data to them successfully
* Verified that variance is triggered when applicable on Enter data page
* Verified the new sub area with Variances are displayed and can be filtered from the Review Data page
* Verified that the Standard report shows the newly added subareas. 
* Verified that the newly added subareas are displayed in the Variance report
* Verified that the newly added subareas are displayed in the Missing data report. 

@cameronpettit I have few issues mentioned above, please let me know if you have questions. Otherwise the page looks good and the functionality works.

**Comment by cameronpettit** [comment]
I have reviewed the changes requested above:

> The options in the dropdown are not sorted alphabetically (not mentioned in the requirement but I am sure client would appreciate it)

Not in designs. Please capture in new ticket if this is in fact a client request.

> Incorrect button label displayed on "Add new subarea?" confirmation overlay -> Should show "Save" instead of "Submit". (refer to the figma file for requirement here: https://www.figma.com/design/yoMhvO0KZvsM6qoqwuIjpt/Attendance-%26-Revenue?node-id=6894-62187&t=81AiijMOTeT1Ybeo-1)

Addressed in https://github.com/bcgov/bcparks-ar-admin/pull/447. Changed to 'Save'

> The labels and values on the "Add new subarea?" confirmation overlay should be displayed in sentence case except for proper nouns.

Addressed in https://github.com/bcgov/bcparks-ar-admin/pull/447. Changed to sentence case - though it should be noted for future purposes that the API expects activities in Capital Case such as 'Backcountry Camping'. This change affects the display in FE only.

> The summary of the record displayed on "Add new subarea?" confirmation overlay is not ordered as per the order given on figma nor the order the fields displayed in the Add form.

Addressed in https://github.com/bcgov/bcparks-ar-admin/pull/447. Updated to reflect designs.

> The dropdown options on Add form must be also in sentence case (eg: Day Use must be displayed as Day use).

Addressed in https://github.com/bcgov/bcparks-ar-admin/pull/447. Changed to sentence case.

> On Activities field on the Add form, the selected options are not spaced out (Enhancement but not a blocker)

This issue is with the form engine and has been captured in https://github.com/digitalspace/ngds-toolkit/issues/22, which I may be able to address as part of [#148](https://github.com/bcgov/reserve-rec-public/issues/148). Will not be addressed as part of this ticket.

> No waiting style displayed until the record get saved and display the success toast message.

Not in designs. Please capture in new ticket if this is in fact a client request.

@manuji @LindsayMacfarlane tagging for visibility

**Comment by manuji** [comment]
Tested on TEST: **Pending**
1. Created a separate ticket: https://github.com/bcgov/bcparks-ar-admin/issues/449
2. Verified that the button labels has been updated to "Save".
3. Verified that the confirmation overlay labels and values are now displayed in sentence case. 
4. Confirmed that the confirmation overlay display the fields in the same order as it is on the Add form. 
5. Confirmed that the options for the Activities are now displayed in sentence case. 
6. Pending testing when fixed by a separate ticket.
7. Created a separate ticket for the waiting style enhancement: https://github.com/bcgov/bcparks-ar-admin/issues/450

-----------------------------------------------

@cameronpettit I found a new issue that I had missed in my previous testing. 

* When viewing the dropdown options while there are validation errors, the options overlapping with the validation errors are not displayed and instead it shows a blank space. Refer to the image below;

<img width="770" alt="Image" src="https://github.com/user-attachments/assets/1147a4b6-2484-485f-9bc3-e750f8f23218" />

Thank you.

**Comment by cameronpettit** [comment]
Interesting bug. Still lies with the NGDS-Toolkit form engine unfortunately, and I have captured it here: https://github.com/digitalspace/ngds-toolkit/issues/24. Will try to address it as part of my other form-engine ticket as the fix seems pretty straightforward - it comes from having loads of typeahead dropdowns stacked on the same page which I don't believe occurs in any of our other products.

As a workaround I have disabled the graphical display of the invalid state in https://github.com/bcgov/bcparks-ar-admin/pull/451. The invalid state will still be enforced but the red border and text will no longer show up, thus preventing this graphical issue from occurring. The submit button does not enable until the whole form is valid. The red invalid state was not part of the designs in the first place but rather a default behaviour of the forms engine. 

@manuji @LindsayMacfarlane tagging for visibility.

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the issue mentioned in my previous comment has been fixed.
* This feature is now ready for UAT and PO review. Please review at your earliest convenience and let me know if this is good to go to PROD @LindsayMacfarlane , @sallyhaynes & @nicolebottoms . 
* Please let me know if you have questions.

**Comment by nicolebottoms** [comment]
there is never a time where there will be 'no region'.

![Image](https://github.com/user-attachments/assets/3890b595-65c6-42ea-85a1-40ba6de5b829)

Is the data heirarchy mapped? i shouldn't be able to put tweedsmuir under kootenay okanagan, much less the section or management area.

![Image](https://github.com/user-attachments/assets/ab19c68a-8ac2-4bfa-b116-c803395394cf)

i can't actually submit to test this, it keeps saying refresh page?

![Image](https://github.com/user-attachments/assets/18a309b6-132d-4e8f-878d-39d3be75849e)

the park name and orc is blank in the submit screen

![Image](https://github.com/user-attachments/assets/e1d82175-c42b-46a1-a037-705c931e56d9)

**Comment by manuji** [comment]
1. Thanks @nicolebottoms for the feedback. @cameronpettit do you think we can remove the "No Region" from the dropdown for the Region field? 
2. As far as I know, we haven't mapped the data to Parks, but once a Region is selected the subsequent fields have been mapped and only show what is relevant to the previous selection. Please correct me if I am wrong @cameronpettit . 
3. @nicolebottoms , looks like you have to clear cache and reload the TEST environment. If you still see the error message when saving the record please let me know we can check that together over a call. I double checked and I cannot recreate the issues you mentioned above.

**Comment by nicolebottoms** [comment]
hey i still get the error message after clearing my cache.
its weird because it still doesn't show the park name or orc when the submit box comes up.

![Image](https://github.com/user-attachments/assets/9ac0329a-378b-437e-a69d-b1092e22a68d)

**Comment by manuji** [comment]
I scheduled us a meeting at 10:30 am tomorrow to check this together @nicolebottoms.

**Comment by manuji** [comment]
@cameronpettit I had a call with @nicolebottoms and;

* I was able to recreate the empty ORCS & park name issue. Given below are the steps to recreate it. 

1. Select the Park from the "park name" field and do not use the ORCS field. 
2. Then fill out the mandatory fields and click "Submit" -> You should see the empty ORCS and Park name fields on the summary page. 

* There is another error Nicole is experiencing but unfortunately I cannot recreate it. I checked her permission and that looks good as well. Given below is a screenshot of the error on the dev console;

<img width="1210" alt="Image" src="https://github.com/user-attachments/assets/f8827d2c-36c1-4b36-92e2-4cf89476c65f" />

* As per Nicole's previous comments we should remove the "No Region" from the dropdown for the Region field. 
* She further asked about the mapping between the Parks and the subsequent data fields, if you can please review and comment about that, it would be great. For further details please check Nicole's previous comments. 

Assigning this back to you @cameronpettit .

**Comment by manuji** [comment]
Tested on TEST: **Passed**
* Verified that the issue with blank park ORCS and Park name has been fixed. 
* Created a separate ticket for the other issue: https://github.com/bcgov/bcparks-ar-admin/issues/454
* This ticket is ready for UAT/PO review.

**Comment by cameronpettit** [comment]
@LindsayMacfarlane  @manuji I looked into the last time the `createSubarea` Lambda was called (by Lindsay) and I was able to trace the logs to figure out what the most likely issue is.

There is a point in the `createSubarea` Lambda where Keycloak is called to create a new role for the management of the new subarea.  Importantly, `sysadmin` role that AR system administrators hold does not apply to the Keycloak realm, and the creation of Keycloak roles requires the caller to have Keycloak Realm roles, not just A&R roles.

Manuji and I are both Realm Administrators. Lindsay and Nicole are not, hence the issue in #454 

I have blessed @LindsayMacfarlane and @nicolebottoms with the Keycloak Realm Viewer role, to see if that would be sufficient. If it isn't we have a bit of a problem on our hands. Lindsay could definitely make the case she needs Keycloak Realm Administrator role but Nicole likely cannot. 

I don't think we can/should give everyone who is an A&R `sysadmin` role the KC Realm Admin role. They will have admin access to all KC clients in the realm (DUP, AR, and other products we share the realm with like DOOT). But, I may be wrong about that feeling.

@marklise tagging you for thoughts on this, if you have any ideas for a clever workaround.

**Comment by nicolebottoms** [comment]
well, larger issue is that it didn't fix it. i cleared my cache, and i'm still seeing the error message.

![Image](https://github.com/user-attachments/assets/3ec67d8b-fde5-42ec-838f-ff574146b4d2)

**Comment by LindsayMacfarlane** [comment]
Not fixed for me either. Even in incognito

![Image](https://github.com/user-attachments/assets/001f0e96-4e17-49d0-ac40-5343724ada2d)

**Comment by Dianadec** [comment]
Standup Notes:
- Could create a unique separate role for this application? Keycloak realm role that allows people to create keycloak roles.
cc @cameronpettit  @marklise

**Comment by nicolebottoms** [comment]
@cameronpettit i can add a subarea now!
oddly enough, i can see the sub-areas i tried to add before as well.

![Image](https://github.com/user-attachments/assets/b95e975d-a694-4676-b96e-7966e87a47fe)
but hooray! thank you!

**Comment by cameronpettit** [comment]
@nicolebottoms yep so all the subarea creations you did were successful in the DB but the step where where the system tries to create the KC role fails, so the front end assumes the whole thing fails. Seems like its working now. Can we move this ticket to PO review @LindsayMacfarlane ?

**Comment by LindsayMacfarlane** [comment]
Moving to QA for @manuji to test again (although feel free to push to me if you don't need to rerun any QA testing).

**Comment by manuji** [comment]
Hi @LindsayMacfarlane , the functionality has been tested, and ready or PO review.

**Comment by LindsayMacfarlane** [comment]
Tentative

@manuji - when I tested, I was able to add a sub area; however, that subarea was then not displayed in the 'enter data'. For example, I tried entering a subarea of blungus to Strathcona Park - Lindsay Loop, but when I went to 'Enter Data' the blungus subarea was not available in the drop down menu. Can you please confirm if you get the same results? Thanks!

**Comment by manuji** [comment]
@LindsayMacfarlane I see this record below;

<img width="1302" alt="Image" src="https://github.com/user-attachments/assets/54ce4aec-aaaa-46ec-8f32-8e43bdac6f2e" />

Is that the one you created with the name "Blungus 2"?

**Comment by LindsayMacfarlane** [comment]
@manuji - yes! Does it take time to refresh to see the data in the drop down? Or do I need to refresh as a user to see the data I just entered? It was definitely not there when I was testing.

**Comment by manuji** [comment]
Hi @LindsayMacfarlane , I checked, looks like we have to refresh the page to see the new sub areas as the navigation doesn't refresh the page automatically.

**Comment by davidclaveau** [comment]
Yea it's somewhat a caching issue with the app - you will be required to do a hard refresh in order to pull the new subarea into the app.

I can't recall the exact functions, but essentially there are different functions that run when the app opens (or on a refresh), versus the functions that run when you simply navigate between pages. It's all part of a single-page application designs - usually you're doing the bare minimum in the background in order to _not_ refresh the page and have a bunch of fetch requests and waiting around for load times.

I vaguely recall Cam mentioning in his demo that it would need a refresh to see the newly added subareas.

**Comment by LindsayMacfarlane** [comment]
Thank you @manuji and @davidclaveau for that clarification. Approved on my end and super excited for @sallyhaynes and @nicolebottoms to start using ;)

With that in mind - Nicole/Sally, can you please do a quick test to double check that things are working for you. Then we can push to PROD :)

**Comment by nicolebottoms** [comment]
oh yes, this works perfectly, thank you!!!

**Comment by LindsayMacfarlane** [comment]
Approved and good to go to PROD when ready @manuji !

**Comment by manuji** [comment]
Hi @cameronpettit I deployed this feature to PROD and over to you to run the migration to populate the dropdown fields. Thank you. Please let me know after to run a smoke test on PROD.

**Comment by manuji** [comment]
@cameronpettit has run the migration and the feature is now ready to use. Thanks everyone!
